

```{r, message=FALSE}
library(tidyverse)
library(here)
```


```{r, message=FALSE}
clean_seabirds <- read_csv(here("3_clean_data/clean_seabirds.csv"))
head(clean_seabirds)
```

1. I'll find the bird with the most individual sightings.

```{r}
clean_seabirds %>%
  group_by(bird_common_name, bird_scientific_name, bird_abbrev_name) %>%
  summarise(sightings = n()) %>%
  arrange(desc(sightings)) %>%
  head(1)
```



2. Bird with the highest total count.

```{r}
clean_seabirds %>%
  group_by(bird_common_name, bird_scientific_name, bird_abbrev_name) %>%
  summarise(count = sum(count)) %>% 
  arrange(desc(count)) %>%
  head(1)
```



3. I will find the bird with the highest total count above a latitude of -30.


```{r}
clean_seabirds %>%
  filter(latitude > -30) %>%
  group_by(bird_common_name, bird_scientific_name, bird_abbrev_name) %>%
  summarise(count = sum(count)) %>% 
  arrange(desc(count)) %>%
  head(1)
```



4. I will find out how many different types of birds were only seen in groups of 1.

```{r}
#list birds
clean_seabirds %>%
  group_by(bird_common_name, bird_scientific_name, bird_abbrev_name) %>%
  summarise(count = max(count)) %>% 
  filter(count == 1)

#get count by filtering rows i.e. number of birds
clean_seabirds %>%
  group_by(bird_common_name, bird_scientific_name, bird_abbrev_name) %>%
  summarise(count = max(count)) %>% 
  filter(count == 1) %>%
  nrow()

```



5. Finally, I want to find out the number of penguins that were seen.

```{r}
clean_seabirds %>%
  filter(str_detect(bird_common_name, "penguin")) %>%
  summarise(number_of_penguins_seen = sum(count))
```







