

```{r, message=FALSE}
library(tidyverse)
library(here)
library(readxl)
```



```{r, message=FALSE}
raw_bird_data <- read_excel(here("1_raw_data/seabirds.xls"), sheet = "Bird data by record ID")
```


```{r}
raw_ship_data <- read_excel(here("1_raw_data/seabirds.xls"), sheet = "Ship data by record ID")
```


```{r}
head(raw_bird_data)
head(raw_ship_data)
```


```{r}
# select only columns we need from the birds dataset

needed_bird_data <- raw_bird_data %>%
  select("RECORD ID", "Species common name (taxon [AGE / SEX / PLUMAGE PHASE])", "Species  scientific name (taxon [AGE /SEX /  PLUMAGE PHASE])", "Species abbreviation", "COUNT")
```


```{r}
# select only columns we need from the ship dataset

needed_ship_data <- raw_ship_data %>%
  select("RECORD ID", "LATCELL", "LONGECELL")
```


```{r}
# join ship data and bird record data

joined_bird_ship <- left_join(needed_bird_data, needed_ship_data, "RECORD ID")
```


```{r}
# identify NAs

joined_bird_ship %>%
  filter(is.na(COUNT))
```

```{r}
# decided to get rid of NAs as it is not needed for this analysis

seabirds_no_na <- joined_bird_ship %>%
  drop_na()
```


```{r}
# rename columns

seabirds_clean <- seabirds_no_na %>%
  rename(record_id = "RECORD ID", bird_common_name = "Species common name (taxon [AGE / SEX / PLUMAGE PHASE])", bird_scientific_name = "Species  scientific name (taxon [AGE /SEX /  PLUMAGE PHASE])", bird_abbrev_name = "Species abbreviation", count = COUNT, latitude = LATCELL, longitude = LONGECELL)
head(seabirds_clean)
```


```{r}
head(seabirds_clean)
```


```{r}
write_csv(seabirds_clean, here("3_clean_data/clean_seabirds.csv"))
```






