


```{r, message=FALSE}
library(tidyverse)
library(here)
```


```{r, message=FALSE}
raw_cakes <- read_csv(here("1_raw_data/cake-ingredients-1961.csv"))
raw_cake_codes <- read_csv(here("1_raw_data/cake_ingredient_code.csv"))
```


```{r}
# mistake in raw dataset - replace missing measure data (NA) with correct measure (cup) from dataset and mutate 'sour creamp cup' to 'sour cream'

imputed_cake_code <- raw_cake_codes %>%
  mutate(measure = replace(measure, 
                           is.na(measure), 
                           "cup"))

head(imputed_cake_code)
```


```{r, message=FALSE}
# pivot into long format and perform a left joining of the two datasets so I can perform analysis
cakes_long <- raw_cakes %>%
  pivot_longer(-Cake, names_to = "code", values_to = "amount") %>%
  rename(cake = Cake) %>%
  left_join(imputed_cake_code) %>%
  drop_na(amount) %>%
  mutate(cake = str_trim(cake)) %>%
  select(-code)


```



```{r}
write_csv(cakes_long, here("3_clean_data/clean_cakes.csv"))
```









